services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: g_millsy
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: millsy_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "g_millsy" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  postgres_data: